language: python
branches:
  only:
  - master
python:
- '2.7'
before_install:
- wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
- source ~/.nvm/nvm.sh
- nvm install 5
- node --version
install:
- pip install -U pip
- pip install -r requirements.txt
script:
- make html
after_success:
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build/html
  on:
    branch: master